whitespace_ops_in_indices = true
remove_extra_newlines = true
pipe_to_function_call = true
short_to_long_function_def = true
always_use_return = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = false
join_lines_based_on_source = true
separate_kwargs_with_semicolon = true